# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Vegetables
Ingredient.create(name: 'Apple', measurement: 'g')
Ingredient.create(name: 'Avocado', measurement: 'x')
Ingredient.create(name: 'Aubergine', measurement: 'g')
Ingredient.create(name: 'Asparagus', measurement: 'g')
Ingredient.create(name: 'Broccoli', measurement: 'g')
Ingredient.create(name: 'Banana', measurement: 'g')
Ingredient.create(name: 'Minced beef', measurement: 'g')
Ingredient.create(name: 'Beetroot', measurement: 'g')
Ingredient.create(name: 'Blueberry', measurement: 'g')
Ingredient.create(name: 'Cheddar', measurement: 'g')
Ingredient.create(name: 'Chicken breast', measurement: 'g')
Ingredient.create(name: 'Chicken thigh', measurement: 'g')
Ingredient.create(name: 'Sweetcorn', measurement: 'g')
Ingredient.create(name: 'Cranberry', measurement: 'g')
Ingredient.create(name: 'Kiwi', measurement: 'g')
Ingredient.create(name: 'Grapes', measurement: 'g')
Ingredient.create(name: 'Egg', measurement: 'x')
Ingredient.create(name: 'Raspberry', measurement: 'g')
Ingredient.create(name: 'Cucumber', measurement: 'g')
Ingredient.create(name: 'Courgette', measurement: 'g')
Ingredient.create(name: 'Onion', measurement: 'x')
Ingredient.create(name: 'Red Pepper', measurement: 'x')
Ingredient.create(name: 'Pak Choy', measurement: 'x')
Ingredient.create(name: 'Tomato', measurement: 'g')
Ingredient.create(name: 'Sweet Potato', measurement: 'g')
Ingredient.create(name: 'Spinach', measurement: 'g')
Ingredient.create(name: 'Mushroom', measurement: 'g')
Ingredient.create(name: 'Shallot', measurement: 'x')
Ingredient.create(name: 'Leek', measurement: 'x')
Ingredient.create(name: 'Black lentil', measurement: 'g')
Ingredient.create(name: 'Red lentil', measurement: 'g')
Ingredient.create(name: 'Pumpkin', measurement: 'g')
Ingredient.create(name: 'Mango', measurement: 'g')
Ingredient.create(name: 'Jalepeno', measurement: 'g')
Ingredient.create(name: 'Spring Onion', measurement: 'x')
Ingredient.create(name: 'Pea', measurement: 'g')
Ingredient.create(name: 'Green Chilli', measurement: 'g')
Ingredient.create(name: 'Garlic', measurement: 'cloves')
Ingredient.create(name: 'Fenugreek', measurement: 'tsp')
Ingredient.create(name: 'Shiitake Mushroom', measurement: 'g')
Ingredient.create(name: 'Carrot', measurement: 'g')
Ingredient.create(name: 'Green Pepper', measurement: 'g')
Ingredient.create(name: 'Okra', measurement: 'g')
Ingredient.create(name: 'Potato', measurement: 'g')
Ingredient.create(name: 'Ginger', measurement: 'g')
Ingredient.create(name: 'Milk', measurement: 'ml')
Ingredient.create(name: 'Oats', measurement: 'g')
Ingredient.create(name: 'Orange', measurement: 'x')
Ingredient.create(name: 'Pork mince', measurement: 'g')
Ingredient.create(name: 'Bacon', measurement: 'g')
Ingredient.create(name: 'Pancetta', measurement: 'g')
Ingredient.create(name: 'Pork medallion', measurement: 'g')
Ingredient.create(name: 'Rice', measurement: 'g')
Ingredient.create(name: 'Salmon', measurement: 'g')
Ingredient.create(name: 'Tofu', measurement: 'g')
Ingredient.create(name: 'Water', measurement: 'ml')
Ingredient.create(name: 'Greek Yoghurt', measurement: 'g')
Ingredient.create(name: 'Garam masala', measurement: 'tsp')
Ingredient.create(name: 'Ground cumin', measurement: 'tsp')
Ingredient.create(name: 'Green Cardamoms', measurement: 'x')
Ingredient.create(name: 'Black Cardamoms', measurement: 'x')
Ingredient.create(name: 'Caster sugar', measurement: 'g')